#delim ;

order 

/* Pre-Survey Information */
country_year_id country_name_ltn country_name_off country_code_nuts country_code_iso country_code_wb_a3 
nuts_ltn nuts_id year id gend age income_quintile income_text income_cur income_time method income_group

/* Trust */
TRT_people TRT_govt_local TRT_govt_national TRT_inst_eu TRT_police TRT_prosecutors TRT_pda TRT_judges 
TRT_media TRT_pparties TRT_parliament 

/* Corruption */
ATC_recruitment_public ATC_brbrequest_public ATC_brboffer_public ATC_embezz_priv ATC_embezz_community
ATC_brbrequest_police COR_parliament COR_govt_national COR_govt_local COR_judges COR_prosecutors COR_pda COR_polic
COR_landreg COR_carreg COR_pparties COR_inst_eu ORC_business_culture ORC_pconnections ORC_corimpact ORC_govtefforts
ORC_impartial_measures ORC_citizen_fight COR_3year_change BRB_permit_A BRB_benefits_A BRB_id_A BRB_school_A
BRB_health_A BRB_permit_B BRB_benefits_B BRB_id_B BRB_school_B BRB_health_B 

/* Information Requests */
IPR_rights IPR_easy2read IPR_easy2find IPR_easy2find_online IRE_govtbudget IRE_govtcontracts IRE_disclosure
IRE_campaign 

/* Security */
SEC_walking SEC_home SEC_children SEC_women SEC_lgbt SEC_immigrant SEC_race SEC_street SEC_orgcrime SEC_police

/* Discrimination */
DIS_sex DIS_age DIS_health DIS_ethni DIS_migration DIS_ses DIS_location DIS_religion DIS_family DIS_gender
DIS_politics DIS_exp_1 DIS_exp_2 DIS_exp_3 DIS_exp_4 DIS_exp_5 DIS_exp_6 DIS_exp_7 DIS_exp_8 DIS_exp_9 DIS_exp_10
DIS_exp_11 DIS_exp_12 DIS_exp_98 DIS_exp_99

/* Access to Justice */
AJP_A1_bin AJP_A2_bin AJP_A3_bin AJP_B1_bin AJP_B2_bin AJP_B3_bin AJP_B4_bin AJP_C1_bin AJP_C2_bin AJP_C3_bin
AJP_C4_bin AJP_D1_bin AJP_D2_bin AJP_D3_bin AJP_D4_bin AJP_D5_bin AJP_D6_bin AJP_E1_bin AJP_E2_bin AJP_E3_bin
AJP_F1_bin AJP_F2_bin AJP_G1_bin AJP_G2_bin AJP_G3_bin AJP_H1_bin AJP_H2_bin AJP_H3_bin AJP_I1_bin AJP_J1_bin
AJP_J2_bin AJP_J3_bin AJP_J4_bin AJP_K1_bin AJP_K2_bin AJP_K3_bin AJP_L1_bin AJP_L2_bin AJP_A1_sev AJP_A2_sev
AJP_A3_sev AJP_B1_sev AJP_B2_sev AJP_B3_sev AJP_B4_sev AJP_C1_sev AJP_C2_sev AJP_C3_sev AJP_C4_sev AJP_D1_sev
AJP_D2_sev AJP_D3_sev AJP_D4_sev AJP_D5_sev AJP_D6_sev AJP_E1_sev AJP_E2_sev AJP_E3_sev AJP_F1_sev AJP_F2_sev
AJP_G1_sev AJP_G2_sev AJP_G3_sev AJP_H1_sev AJP_H2_sev AJP_H3_sev AJP_I1_sev AJP_J1_sev AJP_J2_sev AJP_J3_sev
AJP_J4_sev AJP_K1_sev AJP_K2_sev AJP_K3_sev AJP_L1_sev AJP_L2_sev AJP_problem AJD_selfemployment AJD_violence
AJD_information AJD_inst_advice AJD_adviser_1 AJD_adviser_2 AJD_adviser_3 AJD_adviser_4 AJD_adviser_5 AJD_adviser_6
AJD_adviser_7 AJD_adviser_8 AJD_adviser_9 AJD_adviser_98 AJD_adviser_99 AJD_expert_adviser AJD_noadvice_reason
AJR_resolution AJR_noresol_reason AJR_state_noresol AJR_settle_noresol AJR_court_bin AJR_court_contact
AJR_police_bin AJR_police_contact AJR_office_bin AJR_office_contact AJR_relig_bin AJR_relig_contact
AJR_arbitration_bin AJR_arbitration_contact AJR_appeal_bin AJR_appeal_contact AJR_other_bin AJR_other_contact
AJR_state_resol AJR_settle_resol AJR_fair AJR_slow AJR_expensive AJR_outcome AJR_solvingtime AJR_solvingcosts
AJR_costdiff AJR_satis_outcome AJR_satis_ongoing AJE_description_1 AJE_description_2 AJE_description_3
AJE_description_4 AJE_description_5 AJE_description_6 AJE_description_7 AJE_description_8 AJE_description_98 
AJE_description_99 AJE_legalrights AJE_infosource AJE_advice AJE_fairoutcome AJE_health AJE_emotional 
AJE_income AJE_drugs AJE_offwork_time AJE_income_loss AJE_healthcare AJE_healthcare_visits AJE_hospital 
AJE_hospital_time

/* Civic Participation */
CPA_law_langaval CPA_media_freeop CPA_cleanelec_local CPA_freevote CPA_freepolassoc CPA_partdem_congress
CPA_partdem_localgvt CPA_freemedia CPA_cons_cso CPA_cons_citizen CPA_protest CPA_consultation CPA_cso
CPB_compl_pservices CPB_compl_officials CPB_freeassoc CPB_unions CPB_freexp CPB_community CPB_freemedia
CPB_freexp_cso CPB_freexp_pp CPB_freeassem CPB_protest CPB_consultation CPB_cso 
CP_protest CP_consultation CP_cso 

/* Institutional Performance */
LEP_lawacts LEP_investigations
LEP_rightsresp LEP_accountability LEP_exforce LEP_bribesreq LEP_bribesacc LEP_accusation LEP_pdaperformance
CJP_effective CJP_efficient CJP_access CJP_consistent CJP_fairpunishment CJP_resprights CJP_egalitarian
CJP_fairtrial CJP_victimsupport CJP_proofburden CJP_saferights CTZ_gendereq_A CTZ_consrights_A CTZ_laborcond_A
CTZ_envprotect_A CTZ_euvalues_A CTZ_headgovteval_A CTZ_localgovteval_A PAB_censorinfo PAB_censorvoices PAB_blamesoc
PAB_blameext PAB_freecourts PAB_overcourts PAB_judgeprom PAB_attackopp PAB_prosecuteopp CTZ_accountability_A
LEP_safecom LEP_safefam LEP_policehelp LEP_kindpol LEP_indpolinv LEP_indprosecutors LEP_polservpeopl LEP_polservcom
JSE_rightsaware JSE_access2info JSE_access2assis JSE_affordcosts JSE_quickresol JSE_fairoutcomes JSE_equality
JSE_freecorr JSE_polinfluence JSE_indjudges JSE_fairtrial JSE_enforce JSE_mediation CTZ_gendereq_B CTZ_consrights_B
CTZ_laborcond_B CTZ_envprotect_B CTZ_euvalues_B CTZ_headgovteval_B CTZ_localgovteval_B PAB_misinfo PAB_distract
PAB_credibility PAB_centralize PAB_attackmedia PAB_prosecutejourn PAB_emergpower PAB_attackelect PAB_manipulelect
CTZ_accountability_B CTZ_gendereq CTZ_consrights CTZ_laborcond CTZ_envprotect CTZ_euvalues CTZ_headgovteval
CTZ_localgovteval CTZ_accountability

/* Rule of Law */
ROL_equality_sig ROL_indcontrols_sig ROL_abusepower_sig ROL_corruption_sig ROL_constprotection_sig
ROL_courtrulings_sig ROL_freespeech_sig ROL_indgovtbodies_sig ROL_csoinput_sig ROL_civilobedience_sig
ROL_equality_imp ROL_indcontrols_imp ROL_abusepower_imp ROL_corruption_imp ROL_constprotection_imp
ROL_courtrulings_imp ROL_freespeech_imp ROL_indgovtbodies_imp ROL_csoinput_imp ROL_civilobedience_imp 
KNW_rol_1 KNW_rol_2 KNW_rol_3 KNW_rol_98 KNW_rol_99 KNW_justice_1 KNW_justice_2 KNW_justice_3 
KNW_justice_98 KNW_justice_99 KNW_governance_1 KNW_governance_2 KNW_governance_3 KNW_governance_98 
KNW_governance_99 

/* Demographics */
relig ethni ethni_groups nation fin edu emp work wagreement marital mcertificate disability disability2 politics polid
voteintention incpp A1 A2 A3 A4 A5_1 A5_2 A5b A5c A6 A7 income2 PSU SSU interview_length city region urban B1 B2 B3 
qpi1 qpi2a qpi2b qpi2c qpi2d qpi2e qpi2f qpi3a qpi3b qpi3c qpi3d COLOR dweight Strata
;
