/*=================================================================================================================
Project:		EU Subnational 2023
Routine:		Variable renaming
Author(s):		Carlos A. Toruño Paniagua
Dependencies:  	World Justice Project
Creation Date:	September, 2023

Description: 
This dofile is used to rename the variables submitted by each individual polling company to fit the naming system defined 
in the EU-S Codebook. in order for this dofile to run, it is important that the submited dataset fullfills the structure 
detailed in the EU-GPP Data Map. If the data submitted by the polling company does not match the data map, please run the 
respective Country-Wrangling file before applying this routine.


=================================================================================================================*/


/*=================================================================================================================
					1. Variable renaming
=================================================================================================================*/

rename income income_quintile
rename q1a TRT_people
rename q1b TRT_govt_local
rename q1c TRT_govt_national
rename q1d TRT_inst_eu
rename q1e TRT_police
rename q1f TRT_prosecutors
rename q1g TRT_pda
rename q1h TRT_judges
rename q1i TRT_media
rename q1j TRT_pparties
rename q1k TRT_parliament
rename q2a ATC_recruitment_public
rename q2b ATC_brbrequest_public
rename q2c ATC_brboffer_public
rename q2d ATC_embezz_priv
rename q2e ATC_embezz_community
rename q2f ATC_brbrequest_police
rename q3a COR_parliament
rename q3b COR_govt_national
rename q3c COR_govt_local
rename q3d COR_judges
rename q3e COR_prosecutors
rename q3f COR_pda
rename q3g COR_police
rename q3h COR_landreg
rename q3i COR_carreg
rename q3j COR_pparties
rename q3k COR_inst_eu
rename q4a ORC_business_culture
rename q4b ORC_pconnections
rename q4c ORC_corimpact
rename q4d ORC_govtefforts
rename q4e ORC_impartial_measures
rename q4f ORC_citizen_fight
rename q5  COR_3year_change
rename q6a BRB_permit_A
rename q6b BRB_benefits_A
rename q6c BRB_id_A
rename q6d BRB_school_A
rename q6e BRB_health_A
rename q7a BRB_permit_B
rename q7b BRB_benefits_B
rename q7c BRB_id_B
rename q7d BRB_school_B
rename q7e BRB_health_B
rename q8a IPR_rights
rename q8b IPR_easy2read
rename q8c IPR_easy2find
rename q8d IPR_easy2find_online
rename q9a IRE_govtbudget
rename q9b IRE_govtcontracts
rename q9c IRE_disclosure
rename q9d IRE_campaign
rename q10 SEC_walking
rename q11 SEC_home
rename q12a SEC_children
rename q12b SEC_women
rename q12c SEC_lgbt
rename q12d SEC_immigrant
rename q12e SEC_race
rename q12f SEC_street
rename q12g SEC_orgcrime
rename q12h SEC_police
rename q13a DIS_sex
rename q13b DIS_age
rename q13c DIS_health
rename q13d DIS_ethni
rename q13e DIS_migration
rename q13f DIS_ses
rename q13g DIS_location
rename q13h DIS_religion
rename q13i DIS_family
rename q13j DIS_gender
rename q13k DIS_politics
rename q14_1 DIS_exp_1
rename q14_2 DIS_exp_2
rename q14_3 DIS_exp_3
rename q14_4 DIS_exp_4
rename q14_5 DIS_exp_5
rename q14_6 DIS_exp_6
rename q14_7 DIS_exp_7
rename q14_8 DIS_exp_8
rename q14_9 DIS_exp_9
rename q14_10 DIS_exp_10
rename q14_11 DIS_exp_11
rename q14_12 DIS_exp_12
rename q14_98 DIS_exp_98
rename q14_99 DIS_exp_99
rename q15_A1 AJP_A1_bin
rename q15_A2 AJP_A2_bin
rename q15_A3 AJP_A3_bin
rename q15_B1 AJP_B1_bin
rename q15_B2 AJP_B2_bin
rename q15_B3 AJP_B3_bin
rename q15_B4 AJP_B4_bin
rename q15_C1 AJP_C1_bin
rename q15_C2 AJP_C2_bin
rename q15_C3 AJP_C3_bin
rename q15_C4 AJP_C4_bin
rename q15_D1 AJP_D1_bin
rename q15_D2 AJP_D2_bin
rename q15_D3 AJP_D3_bin
rename q15_D4 AJP_D4_bin
rename q15_D5 AJP_D5_bin
rename q15_D6 AJP_D6_bin
rename q15_E1 AJP_E1_bin
rename q15_E2 AJP_E2_bin
rename q15_E3 AJP_E3_bin
rename q15_F1 AJP_F1_bin
rename q15_F2 AJP_F2_bin
rename q15_G1 AJP_G1_bin
rename q15_G2 AJP_G2_bin
rename q15_G3 AJP_G3_bin
rename q15_H1 AJP_H1_bin
rename q15_H2 AJP_H2_bin
rename q15_H3 AJP_H3_bin
rename q15_I1 AJP_I1_bin
rename q15_J1 AJP_J1_bin
rename q15_J2 AJP_J2_bin
rename q15_J3 AJP_J3_bin
rename q15_J4 AJP_J4_bin
rename q15_K1 AJP_K1_bin
rename q15_K2 AJP_K2_bin
rename q15_K3 AJP_K3_bin
rename q15_L1 AJP_L1_bin
rename q15_L2 AJP_L2_bin
rename q16_A1 AJP_A1_sev
rename q16_A2 AJP_A2_sev
rename q16_A3 AJP_A3_sev
rename q16_B1 AJP_B1_sev
rename q16_B2 AJP_B2_sev
rename q16_B3 AJP_B3_sev
rename q16_B4 AJP_B4_sev
rename q16_C1 AJP_C1_sev
rename q16_C2 AJP_C2_sev
rename q16_C3 AJP_C3_sev
rename q16_C4 AJP_C4_sev
rename q16_D1 AJP_D1_sev
rename q16_D2 AJP_D2_sev
rename q16_D3 AJP_D3_sev
rename q16_D4 AJP_D4_sev
rename q16_D5 AJP_D5_sev
rename q16_D6 AJP_D6_sev
rename q16_E1 AJP_E1_sev
rename q16_E2 AJP_E2_sev
rename q16_E3 AJP_E3_sev
rename q16_F1 AJP_F1_sev
rename q16_F2 AJP_F2_sev
rename q16_G1 AJP_G1_sev
rename q16_G2 AJP_G2_sev
rename q16_G3 AJP_G3_sev
rename q16_H1 AJP_H1_sev
rename q16_H2 AJP_H2_sev
rename q16_H3 AJP_H3_sev
rename q16_I1 AJP_I1_sev
rename q16_J1 AJP_J1_sev
rename q16_J2 AJP_J2_sev
rename q16_J3 AJP_J3_sev
rename q16_J4 AJP_J4_sev
rename q16_K1 AJP_K1_sev
rename q16_K2 AJP_K2_sev
rename q16_K3 AJP_K3_sev
rename q16_L1 AJP_L1_sev
rename q16_L2 AJP_L2_sev
rename q17   AJP_problem
rename q18a  AJD_selfemployment
rename q18b  AJD_violence
rename q19   AJD_information
rename q20   AJD_inst_advice
rename q21_1 AJD_adviser_1
rename q21_2 AJD_adviser_2
rename q21_3 AJD_adviser_3
rename q21_4 AJD_adviser_4
rename q21_5 AJD_adviser_5
rename q21_6 AJD_adviser_6
rename q21_7 AJD_adviser_7
rename q21_8 AJD_adviser_8
rename q21_9 AJD_adviser_9
rename q21_98 AJD_adviser_98
rename q21_99 AJD_adviser_99
rename q22 AJD_expert_adviser
rename q23 AJD_noadvice_reason
rename q24 AJR_resolution
rename q25 AJR_noresol_reason
rename q26 AJR_state_noresol
rename q27 AJR_settle_noresol
rename q28a AJR_court_bin
rename q29a AJR_court_contact
rename q28b AJR_police_bin
rename q29b AJR_police_contact
rename q28c AJR_office_bin
rename q29c AJR_office_contact
rename q28d AJR_relig_bin
rename q29d AJR_relig_contact
rename q28e AJR_arbitration_bin
rename q29e AJR_arbitration_contact
rename q28f AJR_appeal_bin
rename q29f AJR_appeal_contact
rename q28g AJR_other_bin
rename q29g AJR_other_contact
rename q30 AJR_state_resol
rename q31 AJR_settle_resol
rename q32a AJR_fair
rename q32b AJR_slow
rename q32c AJR_expensive
rename q33a AJR_outcome
rename q33b AJR_solvingtime
rename q33c AJR_solvingcosts
rename q33d AJR_costdiff
rename q34 AJR_satis_outcome
rename q35 AJR_satis_ongoing
rename q36_1 AJE_description_1
rename q36_2 AJE_description_2
rename q36_3 AJE_description_3
rename q36_4 AJE_description_4
rename q36_5 AJE_description_5
rename q36_6 AJE_description_6
rename q36_7 AJE_description_7
rename q36_8 AJE_description_8
rename q36_98 AJE_description_98
rename q36_99 AJE_description_99
rename q37a AJE_legalrights
rename q37b AJE_infosource
rename q37c AJE_advice
rename q37d AJE_fairoutcome
rename q38a AJE_health
rename q38b AJE_emotional
rename q38c AJE_income
rename q38d AJE_drugs
rename q38e AJE_offwork_time
rename q38f AJE_income_loss
rename q38g AJE_healthcare
rename q38g_1 AJE_healthcare_visits
rename q38h AJE_hospital
rename q38h_1 AJE_hospital_time
rename q39a_G1 CPA_law_langaval
rename q39b_G1 CPA_media_freeop
rename q39c_G1 CPA_cleanelec_local
rename q39d_G1 CPA_freevote
rename q39e_G1 CPA_freepolassoc
rename q39f_G1 CPA_partdem_congress
rename q39g_G1 CPA_partdem_localgvt
rename q39h_G1 CPA_freemedia
rename q39i_G1 CPA_cons_cso
rename q39j_G1 CPA_cons_citizen
rename q40_G1 CPA_protest
rename q41_G1 CPA_consultation
rename q42_G1 CPA_cso
rename q39a_G2 CPB_compl_pservices
rename q39b_G2 CPB_compl_officials
rename q39c_G2 CPB_freeassoc
rename q39d_G2 CPB_unions
rename q39e_G2 CPB_freexp
rename q39f_G2 CPB_community
rename q39g_G2 CPB_freemedia
rename q39h_G2 CPB_freexp_cso
rename q39i_G2 CPB_freexp_pp
rename q39j_G2 CPB_freeassem
rename q40_G2 CPB_protest
rename q41_G2 CPB_consultation
rename q42_G2 CPB_cso
rename q43a_G1 LEP_lawacts
rename q43b_G1 LEP_investigations
rename q43c_G1 LEP_rightsresp
rename q43d_G1 LEP_accountability
rename q43e_G1 LEP_exforce
rename q43f_G1 LEP_bribesreq
rename q43g_G1 LEP_bribesacc
rename q43h_G1 LEP_accusation
rename q43i_G1 LEP_pdaperformance
rename q44a_G1 CJP_effective
rename q44b_G1 CJP_efficient
rename q44c_G1 CJP_access
rename q44d_G1 CJP_consistent
rename q44e_G1 CJP_fairpunishment
rename q44f_G1 CJP_resprights
rename q44g_G1 CJP_egalitarian
rename q44h_G1 CJP_fairtrial
rename q44i_G1 CJP_victimsupport
rename q44j_G1 CJP_proofburden
rename q44k_G1 CJP_saferights
rename q45a_G1 CTZ_gendereq_A
rename q45b_G1 CTZ_consrights_A
rename q45c_G1 CTZ_laborcond_A
rename q45d_G1 CTZ_envprotect_A
rename q45e_G1 CTZ_euvalues_A
rename q46_G1 CTZ_headgovteval_A
rename q47_G1 CTZ_localgovteval_A
rename q48_G1 PAB_censorinfo
rename q49_G1 PAB_censorvoices
rename q50_G1 PAB_blamesoc
rename q51_G1 PAB_blameext
rename q52_G1 PAB_freecourts
rename q53_G1 PAB_overcourts
rename q54_G1 PAB_judgeprom
rename q55_G1 PAB_attackopp
rename q56_G1 PAB_prosecuteopp
rename q57_G1 CTZ_accountability_A
rename q43a_G2 LEP_safecom
rename q43b_G2 LEP_safefam
rename q43c_G2 LEP_policehelp
rename q43d_G2 LEP_kindpol
rename q43e_G2 LEP_indpolinv
rename q43f_G2 LEP_indprosecutors
rename q43g_G2 LEP_polservpeopl
rename q43h_G2 LEP_polservcom
rename q44a_G2 JSE_rightsaware
rename q44b_G2 JSE_access2info
rename q44c_G2 JSE_access2assis
rename q44d_G2 JSE_affordcosts
rename q44e_G2 JSE_quickresol
rename q44f_G2 JSE_fairoutcomes
rename q44g_G2 JSE_equality
rename q44h_G2 JSE_freecorr
rename q44i_G2 JSE_polinfluence
rename q44j_G2 JSE_indjudges
rename q44k_G2 JSE_fairtrial
rename q44l_G2 JSE_enforce
rename q44m_G2 JSE_mediation
rename q45a_G2 CTZ_gendereq_B
rename q45b_G2 CTZ_consrights_B
rename q45c_G2 CTZ_laborcond_B
rename q45d_G2 CTZ_envprotect_B
rename q45e_G2 CTZ_euvalues_B
rename q46_G2 CTZ_headgovteval_B
rename q47_G2 CTZ_localgovteval_B
rename q48_G2 PAB_misinfo
rename q49_G2 PAB_distract
rename q50_G2 PAB_credibility
rename q51_G2 PAB_centralize
rename q52_G2 PAB_attackmedia
rename q53_G2 PAB_prosecutejourn
rename q54_G2 PAB_emergpower
rename q55_G2 PAB_attackelect
rename q56_G2 PAB_manipulelect
rename q57_G2 CTZ_accountability_B
rename q58a ROL_equality_sig
rename q58b ROL_indcontrols_sig
rename q58c ROL_abusepower_sig
rename q58d ROL_corruption_sig
rename q58e ROL_constprotection_sig
rename q58f ROL_courtrulings_sig
rename q58g ROL_freespeech_sig
rename q58h ROL_indgovtbodies_sig
rename q58i ROL_csoinput_sig
rename q58j ROL_civilobedience_sig
rename q59a ROL_equality_imp
rename q59b ROL_indcontrols_imp
rename q59c ROL_abusepower_imp
rename q59d ROL_corruption_imp
rename q59e ROL_constprotection_imp
rename q59f ROL_courtrulings_imp
rename q59g ROL_freespeech_imp
rename q59h ROL_indgovtbodies_imp
rename q59i ROL_csoinput_imp
rename q59j ROL_civilobedience_imp
rename q60_G1_1  KNW_rol_1
rename q60_G1_2  KNW_rol_2
rename q60_G1_3  KNW_rol_3
rename q60_G1_98 KNW_rol_98
rename q60_G1_99 KNW_rol_99
rename q60_G2_1  KNW_justice_1
rename q60_G2_2  KNW_justice_2
rename q60_G2_3  KNW_justice_3
rename q60_G2_98 KNW_justice_98
rename q60_G2_99 KNW_justice_99
rename q60_G3_1  KNW_governance_1
rename q60_G3_2  KNW_governance_2
rename q60_G3_3  KNW_governance_3
rename q60_G3_98 KNW_governance_98
rename q60_G3_99 KNW_governance_99
rename paff1 polid
rename paff2 voteintention
rename Income2 income2
rename Interview_length interview_length
rename City city
rename Region region
rename Urban urban
